[dx650]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
auth=dx650-auth
aors=dx650-aor

[dx650-auth]
type=auth
auth_type=userpass
username=EXTENSION
password=PASSWORD

[dx650-aor]
type=aor
max_contacts=1
